gazebo_ros_control:
  pid_gains:
    front_left_shoulder  : {p: 900, i: 20, d: 0.9}
    front_left_leg       : {p: 900, i: 20, d: 0.9}
    front_left_foot      : {p: 900, i: 20, d: 0.9}
    front_right_shoulder : {p: 900, i: 20, d: 0.9}
    front_right_leg      : {p: 900, i: 20, d: 0.9}
    front_right_foot     : {p: 900, i: 20, d: 0.9}
    rear_left_shoulder   : {p: 900, i: 20, d: 0.9}
    rear_left_leg        : {p: 900, i: 20, d: 0.9}
    rear_left_foot       : {p: 900, i: 20, d: 0.9}
    rear_right_shoulder  : {p: 900, i: 20, d: 0.9}
    rear_right_leg       : {p: 900, i: 20, d: 0.9}
    rear_right_foot      : {p: 900, i: 20, d: 0.9}
